#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/mdlite
#
# IDENTIFICATION
#    $PostgreSQL: pgsql/src/backend/utils/mdlite/Makefile,v 1.15 2015/11/11 17:45:09 
#
#-------------------------------------------------------------------------

subdir = src/backend/utils/mdlite
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = mdlite_global_generation.o mdlite_local_generation.o mdlite_utils.o \
       mdlite_inv_translator.o

include $(top_srcdir)/src/backend/common.mk
