#############
# RESOURCES #
#############
resources:
- name: gpdb_src
  type: git
  source:
    branch: concourse_perf
    private_key: {{gpdb_deploy_key}}
    uri: git@github.com:hardikar/gpdb.git


########
# JOBS #
########
jobs:
- name: provision
  max_in_flight: 1
  plan:
  - aggregate:
    - get: gpdb_src
      params:
        submodules: none
      trigger: true
  - task: provision_instance
    file: gpdb_src/concourse/provision.yml
    params:
      AWS_SECRET_KEY : "FO"
      AWS_ACCESS_KEY : "FA"
      AWS_KEYPAIR : "keypair"
      AMI : "ami"
      INSTANCE_TYPE : "instance type"
      VPC_ID : "vpc=id"
      SUBNET_ID : "subnet-id"
      SSH_USER : "centos"
      IMAGE_NAME : "Greenplum Database Virtual Appliance"
      TENANCY : "default"

