#############
# RESOURCES #
#############
resources:
- name: gpdb_src
  type: git
  source:
    branch: concourse_perf
    private_key: {{gpdb_deploy_key}}
    uri: git@github.com:hardikar/gpdb.git


########
# JOBS #
########
jobs:
- name: provision
  max_in_flight: 1
  plan:
  - aggregate:
    - get: gpdb_src
      params:
        submodules: none
      trigger: true
  - task: provision_instance
    file: gpdb_src/concourse/provision.yml
    params:
      AWS_ACCESS_KEY_ID : {{aws-access_key_id}}
      AWS_SECRET_ACCESS_KEY : {{aws-secret_access_key}}
      AWS_KEYPAIR : "gporca"
      AWS_REGION : "us-west-1"
      AMI : "ami-7f7ab01f"
      INSTANCE_TYPE : "t1.micro"
      VPC_ID : "vpc=id"
      SUBNET_ID : "subnet-id"
      SSH_USER : "centos"
      TENANCY : "default"

