#############
# RESOURCES #
#############
resources:
- name: gpdb_src
  type: git
  source:
    branch: concourse_perf
    private_key: {{gpdb_deploy_key}}
    uri: git@github.com:hardikar/gpdb.git

- name: instance_ids
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{aws-secret-access-key}}
    versioned_file: instance_ids.txt

########
# JOBS #
########
jobs:
- name: provision
  max_in_flight: 1
  plan:
  - aggregate:
    - get: gpdb_src
      params:
        submodules: none
      trigger: true
  - task: provision_instance
    file: gpdb_src/concourse/provision.yml
    params:
      AWS_ACCESS_KEY : {{aws-access-key-id}}
      AWS_SECRET_KEY : {{aws-secret-access-key}}
      AWS_KEYPAIR : "gporca"
      AWS_REGION : "us-west-2"
      AMI : "ami-7f7ab01f"
      INSTANCE_TYPE : "t2.micro"
      INSTANCE_NAME : "qp-perf-test0"
      VPC_ID : "vpc=id"
      SUBNET_ID : "subnet-id"
      SSH_USER : "centos"
      TENANCY : "default"
      WAIT_SECS : "30"
      RETRIES : "10"
  - put: instance_ids
    params:
      file: output/instance_ids.txt

